"""Strategy IR -> a standalone, reproducible Python runner.

Shipped inside every delivery ZIP so the result can be re-verified independently:
the reviewer installs ``krish``, drops in the IR JSON, and gets the same numbers.
A backtest nobody can reproduce is a screenshot, not evidence.
"""

from __future__ import annotations

from ..ir.schema import StrategyIR

_TEMPLATE = '''#!/usr/bin/env python3
"""Reproduce the KRISH backtest for: {name}

  {asset} {timeframe} | style: {style} | IR id: {ir_id}
  Generated by KRISH. Do not edit the logic here - edit strategy.json and re-run.

Usage:
    pip install -e path/to/krish/backend
    python run_backtest.py                 # full + in-sample + out-of-sample
    python run_backtest.py --walk-forward  # add walk-forward folds
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from krish.backtest.engine import BacktestConfig, split_backtest, walk_forward
from krish.data.providers import fetch_ohlcv
from krish.ir.schema import StrategyIR

HERE = Path(__file__).parent
IR_PATH = HERE / "strategy.json"


def main() -> None:
    parser = argparse.ArgumentParser(description="Reproduce a KRISH backtest")
    parser.add_argument("--walk-forward", action="store_true", help="also run walk-forward folds")
    parser.add_argument("--folds", type=int, default=4)
    parser.add_argument("--balance", type=float, default={balance})
    args = parser.parse_args()

    ir = StrategyIR.model_validate(json.loads(IR_PATH.read_text()))
    print(ir.describe())
    print()

    frame = fetch_ohlcv(ir.asset, ir.timeframe)
    print(f"{{len(frame)}} bars: {{frame.index[0]}} -> {{frame.index[-1]}}")

    config = BacktestConfig(initial_balance=args.balance, oos_fraction={oos_fraction})
    result = split_backtest(ir, frame, config=config)
    if result.get("error"):
        raise SystemExit(f"backtest failed: {{result['error']}}")

    print()
    print(
        f"{{'segment':<10}} {{'trades':>7}} {{'sharpe':>8}} {{'PF':>7}} "
        f"{{'maxDD%':>8}} {{'ret%':>9}}"
    )
    for segment in ("full", "is", "oos"):
        m = result[segment]["metrics"]
        print(
            f"{{segment:<10}} {{m.get('trades', 0):>7}} {{m.get('sharpe', 0):>8.3f}} "
            f"{{m.get('profit_factor', 0):>7.2f}} {{m.get('max_drawdown_pct', 0):>8.2f}} "
            f"{{m.get('total_return_pct', 0):>9.2f}}"
        )
    print()
    print(f"robust score (OOS)   : {{result['robust_score']}}")
    print(f"IS->OOS Sharpe ratio : {{result['sharpe_retention']}}")

    if args.walk_forward:
        wf = walk_forward(ir, frame, folds=args.folds, config=config)
        print()
        print("walk-forward:")
        for fold in wf.get("folds", []):
            print(
                f"  fold {{fold['fold']}}: trades={{fold['trades']}} "
                f"sharpe={{fold['sharpe']}} return={{fold['return_pct']}}%"
            )
        print(f"  consistency: {{wf.get('consistency')}} ({{wf.get('profitable_folds')}}"
              f"/{{wf.get('fold_count')}} eras profitable)")


if __name__ == "__main__":
    main()
'''


def to_python_runner(
    ir: StrategyIR, *, balance: float = 10_000.0, oos_fraction: float = 0.3
) -> str:
    return _TEMPLATE.format(
        name=ir.name,
        asset=ir.asset,
        timeframe=ir.timeframe,
        style=ir.style,
        ir_id=ir.id,
        balance=balance,
        oos_fraction=oos_fraction,
    )


__all__ = ["to_python_runner"]
